CREATE TABLE IF NOT EXISTS `tax_exports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `business_expenses` decimal(38,2) DEFAULT NULL,
  `business_income` decimal(38,2) DEFAULT NULL,
  `business_mileage` decimal(38,2) DEFAULT NULL,
  `capital_gains` decimal(38,2) DEFAULT NULL,
  `capital_losses` decimal(38,2) DEFAULT NULL,
  `charitable_donations` decimal(38,2) DEFAULT NULL,
  `compliance_notes` varchar(1000) DEFAULT NULL,
  `deductible_categories` varchar(3000) DEFAULT NULL,
  `deductible_transactions` int DEFAULT NULL,
  `download_count` int DEFAULT NULL,
  `end_date` date NOT NULL,
  `error_message` varchar(1000) DEFAULT NULL,
  `excluded_categories` varchar(2000) DEFAULT NULL,
  `expires_at` date DEFAULT NULL,
  `export_configuration` varchar(2000) DEFAULT NULL,
  `export_type` enum('BUSINESS_EXPENSES','CHARITABLE_DONATIONS','CUSTOM_PERIOD','DEDUCTIBLE_ONLY','EXPENSES_ONLY','FULL_YEAR','INCOME_ONLY','INVESTMENT_REPORT','MEDICAL_EXPENSES','QUARTERLY') NOT NULL,
  `file_name` varchar(500) NOT NULL,
  `file_size` bigint NOT NULL,
  `file_url` longtext,
  `format` enum('CSV','CUSTOM','EXCEL','JSON','PDF','QUICKBOOKS','TURBOTAX','TXT','XML') NOT NULL,
  `generated_at` date DEFAULT NULL,
  `generated_by` varchar(500) DEFAULT NULL,
  `include_attachments` bit(1) NOT NULL,
  `include_notes` bit(1) NOT NULL,
  `include_receipts` bit(1) NOT NULL,
  `included_categories` varchar(2000) DEFAULT NULL,
  `income_breakdown` varchar(3000) DEFAULT NULL,
  `interest_paid` decimal(38,2) DEFAULT NULL,
  `interest_received` decimal(38,2) DEFAULT NULL,
  `investment_income` decimal(38,2) DEFAULT NULL,
  `is_compliant` bit(1) NOT NULL,
  `last_downloaded_at` date DEFAULT NULL,
  `medical_expenses` decimal(38,2) DEFAULT NULL,
  `net_taxable_income` decimal(38,2) DEFAULT NULL,
  `processing_notes` varchar(1000) DEFAULT NULL,
  `start_date` date NOT NULL,
  `status` enum('COMPLETED','DELETED','EXPIRED','FAILED','PENDING','PROCESSING') NOT NULL,
  `tax_authority` varchar(100) DEFAULT NULL,
  `tax_id` varchar(255) DEFAULT NULL,
  `tax_region` varchar(100) DEFAULT NULL,
  `tax_year` int NOT NULL,
  `total_deductible_expenses` decimal(38,2) DEFAULT NULL,
  `total_expenses` decimal(38,2) DEFAULT NULL,
  `total_income` decimal(38,2) DEFAULT NULL,
  `total_non_deductible_expenses` decimal(38,2) DEFAULT NULL,
  `total_transactions` int DEFAULT NULL,
  `warnings` varchar(2000) DEFAULT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_tax_exports_user` (`user_id`),
  CONSTRAINT fk_tax_exports_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
