apiVersion: networking.k8s.io/1
kind: Ingress
metadata:
  name: takatrack-ingress
  namespace: takatrack
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: <ACM_CERTIFICATE_ARN>
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
  - host: takatrack.puspo.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /v3/api-docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
