apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: takatrack-ingress
  namespace: takatrack
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:135247151840:certificate/dfb86a42-ffc3-4413-a6b9-caf2e6e5742a
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
  - host: takatrack.puspo.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /swagger-ui
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
      - path: /v3/api-docs
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 80
