apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: takatrack
data:
  db_url: "jdbc:mysql://<RDS_ENDPOINT>:3306/takatrack"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: takatrack
type: Opaque
data:
  db_username: <BASE64_USERNAME>
  db_password: <BASE64_PASSWORD>
  gemini_api_key: <BASE64_GEMINI_API_KEY>
