apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: takatrack
data:
  db_url: "jdbc:mysql://takatrack-db.cwl62cq0ol75.us-east-1.rds.amazonaws.com:3306/takatrack"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: takatrack
type: Opaque
data:
  db_username: dGFrYXRyYWNr
  db_password: TWRBc2hpa3VyMTIzNA==
  gemini_api_key: QUl6YVN5QkE5c3kzRlFUVW9wWmVFSGJMUDN0bEdGUjk5TTFYWUNj
